# Generated by Django 2.0.5 on 2018-06-07 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0003_auto_20180531_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.URLField(null=True),
        ),
    ]
