# Generated by Django 2.0.5 on 2018-06-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0005_auto_20180609_1524'),
        ('Database', '0004_auto_20180609_1622'),
    ]

    operations = [
    ]
