# Generated by Django 2.0.5 on 2018-06-10 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0006_merge_20180610_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.IntegerField()),
                ('Sex', models.IntegerField(null=True)),
                ('first_name_1', models.TextField()),
                ('last_name_1', models.TextField()),
                ('Password', models.CharField(max_length=20, null=True)),
                ('Years', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('days', models.IntegerField()),
                ('first_name_2', models.TextField()),
                ('last_name_2', models.TextField()),
                ('company', models.TextField()),
                ('Adress', models.TextField()),
                ('Adress_line_2', models.TextField()),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('Zip', models.CharField(max_length=20, null=True)),
                ('country', models.CharField(max_length=20, null=True)),
                ('aditionalInfo', models.TextField()),
                ('phone', models.IntegerField()),
                ('mobile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.IntegerField()),
                ('Item', models.TextField(null=True)),
            ],
        ),
    ]
