# Generated by Django 2.0.5 on 2018-06-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Database', '0007_user_1_userprod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
